/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConformidadeRouteImport } from './routes/conformidade'
import { Route as OperacaoRouteImport } from './routes/operacao'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RenovacoesRouteImport } from './routes/renovacoes'
import { Route as ChamadosIndexRouteImport } from './routes/chamados.index'
import { Route as ChamadosIdRouteImport } from './routes/chamados.$id'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as FinanceiroCaixaRouteImport } from './routes/financeiro.caixa'
import { Route as FinanceiroPagarRouteImport } from './routes/financeiro.pagar'
import { Route as FinanceiroPlanosRouteImport } from './routes/financeiro.planos'
import { Route as FinanceiroReceberRouteImport } from './routes/financeiro.receber'
import { Route as SolicitacoesIdRouteImport } from './routes/solicitacoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformidadeRoute = ConformidadeRouteImport.update({
  id: '/conformidade',
  path: '/conformidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovacoesRoute = RenovacoesRouteImport.update({
  id: '/renovacoes',
  path: '/renovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIndexRoute = ChamadosIndexRouteImport.update({
  id: '/chamados/',
  path: '/chamados/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIdRoute = ChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroCaixaRoute = FinanceiroCaixaRouteImport.update({
  id: '/financeiro/caixa',
  path: '/financeiro/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroPagarRoute = FinanceiroPagarRouteImport.update({
  id: '/financeiro/pagar',
  path: '/financeiro/pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroPlanosRoute = FinanceiroPlanosRouteImport.update({
  id: '/financeiro/planos',
  path: '/financeiro/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroReceberRoute = FinanceiroReceberRouteImport.update({
  id: '/financeiro/receber',
  path: '/financeiro/receber',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacoesIdRoute = SolicitacoesIdRouteImport.update({
  id: '/solicitacoes/$id',
  path: '/solicitacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/chat': typeof ChatRoute
  '/conformidade': typeof ConformidadeRoute
  '/operacao': typeof OperacaoRoute
  '/portal': typeof PortalRoute
  '/renovacoes': typeof RenovacoesRoute
  '/chamados/$id': typeof ChamadosIdRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/pagar': typeof FinanceiroPagarRoute
  '/financeiro/planos': typeof FinanceiroPlanosRoute
  '/financeiro/receber': typeof FinanceiroReceberRoute
  '/solicitacoes/$id': typeof SolicitacoesIdRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/chat': typeof ChatRoute
  '/conformidade': typeof ConformidadeRoute
  '/operacao': typeof OperacaoRoute
  '/portal': typeof PortalRoute
  '/renovacoes': typeof RenovacoesRoute
  '/chamados/$id': typeof ChamadosIdRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/pagar': typeof FinanceiroPagarRoute
  '/financeiro/planos': typeof FinanceiroPlanosRoute
  '/financeiro/receber': typeof FinanceiroReceberRoute
  '/solicitacoes/$id': typeof SolicitacoesIdRoute
  '/chamados': typeof ChamadosIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/chat': typeof ChatRoute
  '/conformidade': typeof ConformidadeRoute
  '/operacao': typeof OperacaoRoute
  '/portal': typeof PortalRoute
  '/renovacoes': typeof RenovacoesRoute
  '/chamados/$id': typeof ChamadosIdRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/pagar': typeof FinanceiroPagarRoute
  '/financeiro/planos': typeof FinanceiroPlanosRoute
  '/financeiro/receber': typeof FinanceiroReceberRoute
  '/solicitacoes/$id': typeof SolicitacoesIdRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/chat'
    | '/conformidade'
    | '/operacao'
    | '/portal'
    | '/renovacoes'
    | '/chamados/$id'
    | '/clientes/$id'
    | '/financeiro/caixa'
    | '/financeiro/pagar'
    | '/financeiro/planos'
    | '/financeiro/receber'
    | '/solicitacoes/$id'
    | '/chamados/'
    | '/clientes/'
    | '/financeiro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/chat'
    | '/conformidade'
    | '/operacao'
    | '/portal'
    | '/renovacoes'
    | '/chamados/$id'
    | '/clientes/$id'
    | '/financeiro/caixa'
    | '/financeiro/pagar'
    | '/financeiro/planos'
    | '/financeiro/receber'
    | '/solicitacoes/$id'
    | '/chamados'
    | '/clientes'
    | '/financeiro'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/chat'
    | '/conformidade'
    | '/operacao'
    | '/portal'
    | '/renovacoes'
    | '/chamados/$id'
    | '/clientes/$id'
    | '/financeiro/caixa'
    | '/financeiro/pagar'
    | '/financeiro/planos'
    | '/financeiro/receber'
    | '/solicitacoes/$id'
    | '/chamados/'
    | '/clientes/'
    | '/financeiro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ChatRoute: typeof ChatRoute
  ConformidadeRoute: typeof ConformidadeRoute
  OperacaoRoute: typeof OperacaoRoute
  PortalRoute: typeof PortalRoute
  RenovacoesRoute: typeof RenovacoesRoute
  ChamadosIdRoute: typeof ChamadosIdRoute
  ClientesIdRoute: typeof ClientesIdRoute
  FinanceiroCaixaRoute: typeof FinanceiroCaixaRoute
  FinanceiroPagarRoute: typeof FinanceiroPagarRoute
  FinanceiroPlanosRoute: typeof FinanceiroPlanosRoute
  FinanceiroReceberRoute: typeof FinanceiroReceberRoute
  SolicitacoesIdRoute: typeof SolicitacoesIdRoute
  ChamadosIndexRoute: typeof ChamadosIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformidade': {
      id: '/conformidade'
      path: '/conformidade'
      fullPath: '/conformidade'
      preLoaderRoute: typeof ConformidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovacoes': {
      id: '/renovacoes'
      path: '/renovacoes'
      fullPath: '/renovacoes'
      preLoaderRoute: typeof RenovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/': {
      id: '/chamados/'
      path: '/chamados'
      fullPath: '/chamados/'
      preLoaderRoute: typeof ChamadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/$id': {
      id: '/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof ChamadosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/caixa': {
      id: '/financeiro/caixa'
      path: '/financeiro/caixa'
      fullPath: '/financeiro/caixa'
      preLoaderRoute: typeof FinanceiroCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/pagar': {
      id: '/financeiro/pagar'
      path: '/financeiro/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof FinanceiroPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/planos': {
      id: '/financeiro/planos'
      path: '/financeiro/planos'
      fullPath: '/financeiro/planos'
      preLoaderRoute: typeof FinanceiroPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/receber': {
      id: '/financeiro/receber'
      path: '/financeiro/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof FinanceiroReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacoes/$id': {
      id: '/solicitacoes/$id'
      path: '/solicitacoes/$id'
      fullPath: '/solicitacoes/$id'
      preLoaderRoute: typeof SolicitacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ChatRoute: ChatRoute,
  ConformidadeRoute: ConformidadeRoute,
  OperacaoRoute: OperacaoRoute,
  PortalRoute: PortalRoute,
  RenovacoesRoute: RenovacoesRoute,
  ChamadosIdRoute: ChamadosIdRoute,
  ClientesIdRoute: ClientesIdRoute,
  FinanceiroCaixaRoute: FinanceiroCaixaRoute,
  FinanceiroPagarRoute: FinanceiroPagarRoute,
  FinanceiroPlanosRoute: FinanceiroPlanosRoute,
  FinanceiroReceberRoute: FinanceiroReceberRoute,
  SolicitacoesIdRoute: SolicitacoesIdRoute,
  ChamadosIndexRoute: ChamadosIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
